server.port=19000
spring.application.name=crud_produto
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

#database

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:produtosdb}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# JPA Configuration
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

# Logging Configuration
logging.level.root=WARN
logging.level.co.ao.isaf.crud_produto=INFO
logging.level.co.ao.isaf.crud_produto.api.controller=DEBUG
logging.level.co.ao.isaf.crud_produto.api.service=DEBUG
logging.level.co.ao.isaf.crud_produto.config=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
